### ISSUE TITLE
Rename variable

### ISSUE THREAD

**Issue by bondrewd** [ToruNiina/Mjolnir#8]
I think the equilibrium value (length, angle, etc.) of a potential should be called "var_eq" instead of "var_native" because "native" applies only when this value is taken from the native conformation of a biomolecule (crystal structure, etc.).

**Comment by bondrewd** [comment]
What about "eq_val"? Since there are many interactions: bond, angle, go, etc. 

```C
potential = "Harmonic"
parameters = [
{indices = [ 0, 1], eq_val = 3.8, k = 100.0},
# ...
]
```

Or maybe just "eq"

```C
potential = "Harmonic"
parameters = [
{indices = [ 0, 1], eq = 3.8, k = 100.0},
# ...
]
```

**Comment by ToruNiina** [comment]
I think just `eq` is clear enough. This abbreviation (equilibrium -> eq) is widely used.
too long line makes it difficult to read/write a file (although now it is short enough).

**Comment by bondrewd** [comment]
Then "eq" should be ok! :)

**Comment by ToruNiina** [comment]
Thank you for your excellent suggestion. I renamed the variables.
